### ISSUE TITLE
Add the mod to the contentdb

### ISSUE THREAD

**Issue by BuckarooBanzay** [berengma/farming_nextgen#17]
it would be a nice addition :wink: if you need help, let me know

**Comment by berengma** [comment]
There is a problem in the CDB. Because I once deleted it from there, it does not show up in my list of mods that could be added.

**Comment by BuckarooBanzay** [comment]
Thanks @rubenwardy for restoring the deleted package :+1: 
https://content.minetest.net/packages/Gundul/farming_nextgen/

**Comment by berengma** [comment]
@BuckarooBanzay added to CDB, waiting for approval.
