### ISSUE TITLE
farming:barley_8 Does not get harvested

### ISSUE THREAD

**Issue by MCLV-pandorabox** [berengma/farming_nextgen#23]
in harvester.lua I do see
farmingNG.harvester_names["farming:barley_7"]	= true
 in there twice, I think the last one should be farming:barley_8

Thanks for your work

**Comment by SwissalpS** [comment]
lines 15 and 88

**Comment by OgelGames** [comment]
They have different mod names:
https://github.com/berengma/farming_nextgen/blob/657bf2850f0079837d4b57188793ec650812ffc0/harvester.lua#L15
https://github.com/berengma/farming_nextgen/blob/657bf2850f0079837d4b57188793ec650812ffc0/harvester.lua#L88
But yeah `farming:barley_8` is missing, somehow I missed that in my last PR.
