### ISSUE TITLE
Sound of seeder/harvester is too loud

### ISSUE THREAD

**Issue by OgelGames** [berengma/farming_nextgen#5]
Compared to other sounds in the game, the seeder/harvester sound is way too loud, especially for headphone users like myself...

**Comment by BobFred7** [comment]
https://github.com/berengma/farming_nextgen/blob/master/harvester.lua#L160-L161
https://github.com/berengma/farming_nextgen/blob/master/seeder.lua#L318
Reducing the `gain` value might fix this

**Comment by berengma** [comment]
Sorry it took so long, never saw this one before. Fixed now.
