### ISSUE TITLE
Seeder does not work in public farms

### ISSUE THREAD

**Issue by SwissalpS** [berengma/farming_nextgen#9]
At public farms the soil is protected but air above it not. This allows any user to harvest and plant manually.
However seeder checks for protection of node under which seed is to be placed at.
https://github.com/berengma/farming_nextgen/blob/adda1f422fc7925c32c16135a907c6da77af1662/seeder.lua#L364

Shouldn't seeder be checking the node it will actually be modifying, y + 1

**Comment by berengma** [comment]
I will take a look at this.

**Comment by berengma** [comment]
Thanks for pointing that out. Now it works.
